from __future__ import annotations

import sys
import time
from dataclasses import dataclass
from collections import OrderedDict
from pathlib import Path
from typing import Iterator, List

import numpy as np
import pandas as pd
import keras
import tensorflow as tf

from model import MVCNN_Siamese
from swc_util import _load_views_from_npz, _pad_to_same_size, _resize_to_50


@dataclass(frozen=True)
class Config:
    model_dir: str = "./Annotator_Model"
    model_prefix: str = "Annotator_D1-D6_"   # without fold number
    out_dir: str = "./result/unlabel_data_predict"

    # input pairs CSV: columns must include em_id, fc_id; optional score, rank
    pairs_csv: str = "./data/pairs_label/EMxFC_6KK_last.csv"

    # per-neuron views generated by standard_draw
    fc_views_dir: str = "./data/standard_views/FC"
    em_views_dir: str = "./data/standard_views/EM"

    # output resolution
    out_hw: tuple[int, int] = (50, 50)

    # memory control: max number of pairs per chunk
    chunk_pairs: int = 80000

    # resume: if output chunk exists, skip computing this chunk
    skip_existing_chunks: bool = True

    # cache control (LRU by id): limits memory usage when many unique ids appear
    cache_size_fc: int = 2048
    cache_size_em: int = 2048

    # must match training when constructing model for weights loading
    initial_lr: float = 1e-5

    # inference
    threshold: float = 0.5

    # normalization: keep consistent with your training (optional)
    do_minmax_norm: bool = False  # set True if needed

    # logging
    profile_timing: bool = True  # print per-chunk stage timing


class _LRUCache:
    def __init__(self, max_items: int):
        self.max_items = int(max_items)
        self._d: "OrderedDict[str, np.ndarray]" = OrderedDict()

    def get(self, key: str) -> np.ndarray | None:
        if key in self._d:
            self._d.move_to_end(key)
            return self._d[key]
        return None

    def put(self, key: str, value: np.ndarray) -> None:
        if self.max_items <= 0:
            return
        if key in self._d:
            self._d.move_to_end(key)
            self._d[key] = value
            return
        self._d[key] = value
        if len(self._d) > self.max_items:
            self._d.popitem(last=False)


def maybe_minmax_norm(x: np.ndarray) -> np.ndarray:
    x = x.astype(np.float32)
    mn, mx = x.min(), x.max()
    if mx > mn:
        return (x - mn) / (mx - mn)
    return x


def load_model(cfg: Config, model_id: int, input_size: tuple[int, int, int]):
    """Load a single weights-only `.weights.h5` checkpoint by rebuilding the model first."""
    model = MVCNN_Siamese(input_size)

    weights_path = Path(cfg.model_dir) / f"{cfg.model_prefix}{model_id}.weights.h5"
    model.load_weights(weights_path)
    return model


def _append_missing_rows(missing_csv: Path, rows: List[dict]) -> None:
    if not rows:
        return
    df = pd.DataFrame(rows)
    missing_csv.parent.mkdir(parents=True, exist_ok=True)
    header = not missing_csv.exists()
    df.to_csv(missing_csv, index=False, mode="a", header=header)


def main() -> None:
    cfg = Config()

    # model selection: default single model id from argv[1]
    single_model = int(sys.argv[1]) if len(sys.argv) > 1 else 9

    Path(cfg.out_dir).mkdir(parents=True, exist_ok=True)

    pairs_csv = Path(cfg.pairs_csv)
    if not pairs_csv.exists():
        raise FileNotFoundError(f"pairs_csv not found: {pairs_csv}")

    fc_dir = Path(cfg.fc_views_dir)
    em_dir = Path(cfg.em_views_dir)
    if not fc_dir.exists():
        raise FileNotFoundError(f"FC standard views dir not found: {fc_dir}")
    if not em_dir.exists():
        raise FileNotFoundError(f"EM standard views dir not found: {em_dir}")

    out_h, out_w = int(cfg.out_hw[0]), int(cfg.out_hw[1])
    if out_h <= 0 or out_w <= 0:
        raise ValueError(f"Invalid out_hw={cfg.out_hw}")

    print("Pairs CSV:", pairs_csv, flush=True)
    print("FC views dir:", fc_dir, flush=True)
    print("EM views dir:", em_dir, flush=True)

    model = load_model(cfg, single_model, input_size=(out_h, out_w, 3))
    print("Used model:", single_model, flush=True)

    missing_csv = Path(cfg.out_dir) / f"missing_{cfg.model_prefix}{single_model}.csv"

    start = time.time()

    total_rows = 0
    total_found = 0
    total_missing = 0

    for chunk_idx, df in enumerate(pd.read_csv(pairs_csv, chunksize=cfg.chunk_pairs)):
        out_name = f"{cfg.model_prefix}{single_model}_chunk{chunk_idx}.csv"
        out_path = Path(cfg.out_dir) / out_name

        if cfg.skip_existing_chunks and out_path.exists():
            print(f"Skip existing chunk {chunk_idx}: {out_path}", flush=True)
            continue

        if "em_id" not in df.columns or "fc_id" not in df.columns:
            raise KeyError(f"pairs_csv must contain columns em_id, fc_id. got={list(df.columns)}")

        # NOTE: pairs CSV may contain score/rank, but we don't propagate them to keep legacy output format

        # chunk-local LRU caches to cap memory
        fc_cache = _LRUCache(cfg.cache_size_fc)
        em_cache = _LRUCache(cfg.cache_size_em)

        found_fc_ids: List[str] = []
        found_em_ids: List[str] = []
        fc_views_list: List[np.ndarray] = []
        em_views_list: List[np.ndarray] = []

        missing_rows: List[dict] = []

        total_rows += int(len(df))
        print(f"\nChunk {chunk_idx}: {len(df)} rows", flush=True)

        t_collect0 = time.perf_counter() if cfg.profile_timing else 0.0
        t_npz_load = 0.0
        t_pad = 0.0
        t_resize = 0.0
        n_profile_ok = 0

        for row in df.itertuples(index=False):
            em_id = str(getattr(row, "em_id")).strip()
            fc_id = str(getattr(row, "fc_id")).strip()

            fc_npz = fc_dir / f"{fc_id}_views.npz"
            em_npz = em_dir / f"{em_id}_views.npz"

            if not fc_npz.exists() and not em_npz.exists():
                missing_rows.append({"chunk": chunk_idx, "fc_id": fc_id, "em_id": em_id, "reason": "missing_fc_and_em_npz"})
                continue
            if not fc_npz.exists():
                missing_rows.append({"chunk": chunk_idx, "fc_id": fc_id, "em_id": em_id, "reason": "missing_fc_npz"})
                continue
            if not em_npz.exists():
                missing_rows.append({"chunk": chunk_idx, "fc_id": fc_id, "em_id": em_id, "reason": "missing_em_npz"})
                continue

            try:
                t0 = time.perf_counter() if cfg.profile_timing else 0.0
                fc_v = fc_cache.get(fc_id)
                if fc_v is None:
                    fc_v = _load_views_from_npz(fc_npz)
                    fc_cache.put(fc_id, fc_v)

                em_v = em_cache.get(em_id)
                if em_v is None:
                    em_v = _load_views_from_npz(em_npz)
                    em_cache.put(em_id, em_v)
                if cfg.profile_timing:
                    t_npz_load += time.perf_counter() - t0
            except Exception as e:
                missing_rows.append({"chunk": chunk_idx, "fc_id": fc_id, "em_id": em_id, "reason": f"load_error:{type(e).__name__}:{e}"})
                continue

            try:
                t1 = time.perf_counter() if cfg.profile_timing else 0.0
                fc_pad, em_pad = _pad_to_same_size(fc_v, em_v)
                if cfg.profile_timing:
                    t_pad += time.perf_counter() - t1

                t2 = time.perf_counter() if cfg.profile_timing else 0.0
                fc_50 = _resize_to_50(fc_pad, (out_h, out_w))
                em_50 = _resize_to_50(em_pad, (out_h, out_w))
                if cfg.profile_timing:
                    t_resize += time.perf_counter() - t2
            except Exception as e:
                missing_rows.append({"chunk": chunk_idx, "fc_id": fc_id, "em_id": em_id, "reason": f"preprocess_error:{type(e).__name__}:{e}"})
                continue

            found_fc_ids.append(fc_id)
            found_em_ids.append(em_id)
            fc_views_list.append(fc_50)
            em_views_list.append(em_50)
            if cfg.profile_timing:
                n_profile_ok += 1

        t_collect = (time.perf_counter() - t_collect0) if cfg.profile_timing else 0.0

        if cfg.profile_timing:
            other = t_collect - (t_npz_load + t_pad + t_resize)
            denom = max(n_profile_ok, 1)
            print(
                f"[timing_collect] chunk={chunk_idx} load={t_npz_load:.2f}s pad={t_pad:.2f}s "
                f"resize={t_resize:.2f}s other={other:.2f}s "
                f"per_pair_ms(load/pad/resize)={t_npz_load*1000/denom:.2f}/{t_pad*1000/denom:.2f}/{t_resize*1000/denom:.2f} n={n_profile_ok}",
                flush=True,
            )

        _append_missing_rows(missing_csv, missing_rows)
        total_missing += len(missing_rows)

        if not found_fc_ids:
            print(f"No valid pairs in chunk {chunk_idx}, skip prediction", flush=True)
            continue

        fc_np = np.stack(fc_views_list, axis=0)  # (N,3,H,W)
        em_np = np.stack(em_views_list, axis=0)  # (N,3,H,W)
        fc_img = np.transpose(fc_np, (0, 2, 3, 1)).astype(np.float32) / 255.0
        em_img = np.transpose(em_np, (0, 2, 3, 1)).astype(np.float32) / 255.0

        if cfg.do_minmax_norm:
            # NOTE: this normalizes the whole chunk to [0,1] by global min/max.
            fc_img = maybe_minmax_norm(fc_img)
            em_img = maybe_minmax_norm(em_img)

        t_pred0 = time.perf_counter()
        pred = model.predict({"FC": fc_img, "EM": em_img}, verbose=0)
        t_pred = time.perf_counter() - t_pred0
        print("Predict time:", t_pred, "s", flush=True)

        out_df = pd.DataFrame(
            {
                "fc_id": found_fc_ids,
                "em_id": found_em_ids,
                "model_predict": pred.reshape(-1),
            }
        )

        t_write0 = time.perf_counter() if cfg.profile_timing else 0.0
        out_df.to_csv(out_path, index=False)
        t_write = (time.perf_counter() - t_write0) if cfg.profile_timing else 0.0
        total_found += len(out_df)
        print("Saved:", out_path, flush=True)

    print("\nProgram Completed. Total time:", time.time() - start, "s", flush=True)
    print(f"Total input rows: {total_rows}", flush=True)
    print(f"Total predicted pairs: {total_found}", flush=True)
    print(f"Total missing/failed pairs: {total_missing}", flush=True)
    if missing_csv.exists():
        print("Missing report:", missing_csv, flush=True)


if __name__ == "__main__":
    main()
