# %%
import os
import numpy as np
import pandas as pd
from util import load_pkl
from keras.models import *
import time
from collections import defaultdict


model_path = './Annotator_Model/Annotator_D1-D6_0.h5'   # 模型存放路徑
save_folder_path = './result/'                       # 模型預測結果存放路徑
unlabel_path_01 = './data/statistical_results/three_view_pic_rk10' # 使用者上傳的神經做圖資料夾

if not os.path.exists(save_folder_path):
    os.makedirs(save_folder_path)





# %% 
# 筛选出指定文件夹下以 .pkl 结尾的文件並存入列表
file_list_01 = [file_name for file_name in os.listdir(unlabel_path_01) if file_name.endswith('.pkl')]

file_path = [os.path.join(unlabel_path_01, file_name) for file_name in file_list_01]

# 載入模型
model = load_model(model_path, compile=False)   # 模型存放資料夾






# %%
# Initialize dictionaries with default types to store file names and results
data_dict = defaultdict((list))

st = time.time()
print('Start collect')
# Traverse all entries in the parent folder
for pkl_file in file_path:
    # Load the pkl file
    data_lst = load_pkl(pkl_file)
    for data in data_lst:
        # Record neuron data and stack images
        data_dict['source_nrn'].append(data[0])
        data_dict['target_nrn'].append(data[1])
        
        # Images generated by Coronation are in the shape of 3,50,50, needed by CNN as 50,50,3
        data_dict['source_img'].append(np.transpose(data[3], (1, 2, 0)))
        data_dict['target_img'].append(np.transpose(data[4], (1, 2, 0)))

print('End collect')
print('Collected Time used:', time.time()-st)

# %%

source_nrn_lst = data_dict['source_nrn']
target_nrn_lst = data_dict['target_nrn']

# 產生模型輸入numpy array
source_img = np.array(data_dict['source_img'])
target_img = np.array(data_dict['target_img'])


st = time.time()
predict_result = model.predict({'FC':source_img, 'EM':target_img}, verbose=0)
time_used = time.time() - st
print('\nTotal time used:', time_used, f'For {len(source_img)} pairs.')
print('\nAverage time per pair:', time_used/len(source_img))


# 将文件名和计算结果添加到DataFrame
label_df = pd.DataFrame({'source_id': source_nrn_lst, 'target_id': target_nrn_lst, 'score': predict_result.flatten()})# online version

# 排序
label_df = label_df.sort_values(by=['source_id', 'score'], ascending=[True, False])


# 将DataFrame存储为csv文件
label_df.to_csv(save_folder_path+'model_predict.csv', index=False)
print('\nSaved')
print('Program Completed.')
# %%
