# %%
import os
import numpy as np
import pandas as pd
from util import load_pkl
from keras.models import *
from tqdm import tqdm
from collections import defaultdict
import time
import sys



model_path = './Fine_Tune_Model/'   # 加载模型路径
model_name = 'Fine_Tune_Model_150K_'     # 模型名称 不包含后缀数字
save_folder_path = './result/FC-FC_pairs/'

if not os.path.exists(save_folder_path):
    os.makedirs(save_folder_path)


# %%

#傳遞參數模式
single_model = int(sys.argv[1])

# use_model = [5, 6] # [a,b]欲使用之模型編號，從a開始用到到b
use_model = [single_model, single_model+1]

# 对新数据集进行标注
unlabel_path_01 = 'data/statistical_results/FC_FC_316pairs_SN'
# unlabel_path_02 = './data/statistical_results/three_view_pic_rk10to20'

# 筛选出指定文件夹下以 .pkl 结尾的文件並存入列表
file_list_01 = [file_name for file_name in os.listdir(unlabel_path_01) if file_name.endswith('.pkl')]
# file_list_02 = [file_name for file_name in os.listdir(unlabel_path_02) if file_name.endswith('.pkl')]

file_path_01 = [os.path.join(unlabel_path_01, file_name) for file_name in file_list_01]
# file_path_02 = [os.path.join(unlabel_path_02, file_name) for file_name in file_list_02]
file_path = file_path_01 #+ file_path_02


# 计算label

model_lst = []
for i in range(use_model[0], use_model[1]):
    model_filename = model_name +str(i)
    model = load_model(os.path.join(model_path, model_filename+'.h5'))
    model_lst.append(model)

print('Used model:', use_model)

# %%

# 分段完成
sub_length = 20000000

if len(file_path) > sub_length:
    
    num = 0
    while num * sub_length < len(file_path):
        start_idx = int(num * sub_length)
        end_idx = int(min((num + 1) * sub_length, len(file_path)))

        file_path_predict = file_path[start_idx:end_idx]
        print('\nProcess on Num.', start_idx, '~', end_idx)


        data_dict = defaultdict((list))  # Initialize dictionaries with default types to store file names and results

        print('Collecting data..')
        # Traverse all entries in the parent folder
        for pkl_file in tqdm(file_path_predict, total=len(file_path_predict)):
            # Load the pkl file
            data_lst = load_pkl(pkl_file)
            for data in data_lst:
                # Record neuron data and stack images
                data_dict['fc_nrn'].append(data[0])
                data_dict['em_nrn'].append(data[1])
                
                # Images generated by Coronation are in the shape of 3,50,50, needed by CNN as 50,50,3
                data_dict['fc_img'].append(np.transpose(data[3], (1, 2, 0)))
                data_dict['em_img'].append(np.transpose(data[4], (1, 2, 0)))
        # print('End collect')

        fc_nrn_lst = data_dict['fc_nrn']
        em_nrn_lst = data_dict['em_nrn']

        # 產生模型輸入numpy array
        fc_img = np.array(data_dict['fc_img'])
        em_img = np.array(data_dict['em_img'])

        print('Model predicting..')
        predict_lst = []
        for model in model_lst:
            predict_result = model.predict({'FC':fc_img, 'EM':em_img}, verbose=0)
            predict_lst.append(predict_result)
        
        predict_np = np.array(predict_lst)
       
        result_avg = np.mean(predict_np, axis=0)
        result_std = np.std(predict_np, axis=0)
        result_bin = np.where(result_avg > 0.5, 1, 0)

        label_df = pd.DataFrame({'fc_id': fc_nrn_lst, 'em_id': em_nrn_lst, 'model_predict': result_avg.flatten(), 'binary_label': result_bin.flatten(), 'pred_std': result_std.flatten()})

        label_df.to_csv(save_folder_path+'labeled_'+str(num)+'.csv', index=False)
        print('\nSave Num:', num)
        del label_df, data_lst, data_dict
        num += 1
        # del label_df, data_lst, new_data_lst
    
    print('Program Completed.')

else:
    data_dict = defaultdict((list))  # Initialize dictionaries with default types to store file names and results

    print('Collecting data..')
    # Traverse all entries in the parent folder
    for pkl_file in tqdm(file_path, total=len(file_path)):
        # Load the pkl file
        data_lst = load_pkl(pkl_file)
        for data in data_lst:
            # Record neuron data and stack images
            data_dict['fc_nrn'].append(data[0])
            data_dict['em_nrn'].append(data[1])
            
            # Images generated by Coronation are in the shape of 3,50,50, needed by CNN as 50,50,3
            data_dict['fc_img'].append(np.transpose(data[3], (1, 2, 0)))
            data_dict['em_img'].append(np.transpose(data[4], (1, 2, 0)))
    # print('End collect')

    fc_nrn_lst = data_dict['fc_nrn']
    em_nrn_lst = data_dict['em_nrn']

    # 產生模型輸入numpy array
    fc_img = np.array(data_dict['fc_img'])
    em_img = np.array(data_dict['em_img'])

    print('Model predicting..')
    st = time.time()
    predict_lst = []
    for model in model_lst:
        predict_result = model.predict({'FC':fc_img, 'EM':em_img}, verbose=2)
        predict_lst.append(predict_result)
    
    print('Model predict time used:', time.time()-st, 's')

    predict_np = np.array(predict_lst)
    
    result_avg = np.mean(predict_np, axis=0)
    result_std = np.std(predict_np, axis=0)
    result_bin = np.where(result_avg > 0.5, 1, 0)

    label_df = pd.DataFrame({'fc_id': fc_nrn_lst, 'em_id': em_nrn_lst, 'model_predict': result_avg.flatten(), 'binary_label': result_bin.flatten(), 'pred_std': result_std.flatten()})

    # 将DataFrame存储为csv文件
    label_df.to_csv(os.path.join(save_folder_path, model_filename+'.csv'), index=False)
    print('\nSaved')
    print('Program Completed.')
# %%
# # 受限於電腦RAM不足，只能一個一個模型跑的情況下，需要額外的步驟將label.csv合併
# model_name = 'Fine_Tune_Model_150K_'

# file_lst = os.listdir(save_folder_path)
# file_lst = [os.path.join(save_folder_path, filename) for filename in file_lst if model_name in filename]
# print(sorted(file_lst))
# print('Len:',len(file_lst))

# merge_df = None
# i = 0
# for file_path in file_lst:
#     if merge_df is None:
#         merge_df = pd.read_csv(file_path)[['fc_id', 'em_id', 'model_predict']]
#         merge_df.rename(columns={'model_predict': 'model_predict_'+str(i)}, inplace=True)
#         i += 1
#     else:
#         df = pd.read_csv(file_path)[['fc_id', 'em_id', 'model_predict']]
#         df.rename(columns={'model_predict': 'model_predict_'+str(i)}, inplace=True)
#         i += 1

#         merge_df = pd.merge(merge_df, df, on=['fc_id', 'em_id'], how='inner')

# # 重新計算平均值、標準差
# predict_columns = [col for col in merge_df.columns if 'model_predict' in col]
# merge_df['model_predict_avg'] = merge_df[predict_columns].mean(axis=1)
# merge_df['model_predict_std'] = merge_df[predict_columns].std(axis=1)

# # 刪去已存在於human label的組合
# human_label_test = pd.read_csv('./train_test_split/test_split_0_D1-D6.csv')
# human_label_train = pd.read_csv('./train_test_split/train_split_0_D1-D6.csv')
# human_label = pd.concat([human_label_test, human_label_train])

# merge_df = pd.merge(merge_df, human_label, on=['fc_id', 'em_id'], how='left', indicator=True)
# merge_df = merge_df[merge_df['_merge'] == 'left_only']
# merge_df.drop(columns=['score', 'label', '_merge'], inplace=True)

# # 按照std排序
# merge_df_sort = merge_df.sort_values(by='model_predict_std', ascending=True)
# merge_df_sort.rename(columns={'model_predict_avg':'label'}, inplace=True)
# merge_df_sort.to_csv('preTrain_label/preTrain_label_Annotator.csv', index=False)

# %%
# # 複製模塊
# import shutil

# source_path = './data/mapping_data_0.7+'
# target_path = './data/statistical_results/pre_train_map'

# file_list = os.listdir(source_path)
# file_list = [os.path.join(source_path, filename) for filename in file_list if filename.endswith('.pkl')]
# print('Copy file:', len(file_list))
# copy_num = 0
# for path in tqdm(file_list):
#     # 檢查是否已存在
#     if not os.path.exists(os.path.join(target_path, os.path.basename(path))):
#         shutil.copy(path, target_path) 
#         copy_num += 1
# print(copy_num, 'files copied.')
# %%
