# %%
# v2版本是因為冠廷程式修改成ranking_process不運行，因此檔案讀取位置不同，此版本增加一個預處理步驟
#Warning: 以下所有folder路徑必須以"/"結尾
import os
import numpy as np
import pandas as pd
from util import load_pkl
from keras.models import *
import time
from collections import defaultdict


model_path = './Fine_Tune_Model/Fine_Tune_Model_150K_1.h5'         # 模型存放路徑
save_folder = './result/predict_result'                            # 模型預測結果存放路徑

unlabel_pairs_path = './data/.csv'                                 # 冠廷程式初篩後的pairs csv
unlabel_map_folder = './data/mapping_data2/'                       # 使用者上傳的神經做圖資料夾

map_type = 'sn'

# 檢查路徑存在
if not os.path.exists(model_path):
    print('Model not found:', model_path)
    exit()

if not os.path.exists(save_folder):
    os.makedirs(save_folder)

unlabel_pairs_df = pd.read_csv(unlabel_pairs_path)


# %% # 載入模型
model = load_model(model_path)   # 模型存放資料夾






# %%
# Initialize dictionaries with default types to store file names and results
data_dict = defaultdict((list))

st = time.time()
print('Start collect')
# Traverse all entries in the parent folder
for row in unlabel_pairs_df.iterrows():
    source_id = row[1].iloc[0]
    target_id = row[1].iloc[1]
    data_dict['source_id'].append(source_id)   #這裡默認第一列是source第二列是target
    data_dict['target_id'].append(target_id)

    # load the map image
    source_path = unlabel_map_folder + str(source_id) + '.pkl'
    target_path = unlabel_map_folder + str(target_id) + '.pkl'

    source_img = load_pkl(source_path)[map_type]
    target_img = load_pkl(target_path)[map_type]
    
    # Images generated by Coronation are in the shape of 3,50,50, needed by CNN as 50,50,3
    data_dict['source_img'].append(np.transpose(source_img, (1, 2, 0)))
    data_dict['target_img'].append(np.transpose(target_img, (1, 2, 0)))

print('End collect')
print('Collected Time used:', time.time()-st)

# %%

source_id_lst = data_dict['source_id']
target_id_lst = data_dict['target_id']

# 產生模型輸入numpy array
source_img = np.array(data_dict['source_img'])
target_img = np.array(data_dict['target_img'])


st = time.time()
predict_result = model.predict({'FC':source_img, 'EM':target_img}, verbose=0)
time_used = time.time() - st
print('\nTotal time used:', time_used, f'For {len(source_img)} pairs.')
print('\nAverage time per pair:', time_used/len(source_img))


# 将文件名和计算结果添加到DataFrame
label_df = pd.DataFrame({'source_id': source_id_lst, 'target_id': target_id_lst, 'score': predict_result.flatten()})# online version

# 排序
label_df = label_df.sort_values(by=['source_id', 'score'], ascending=[True, False])


# 将DataFrame存储为csv文件
label_df.to_csv(save_folder+'model_predict.csv', index=False)
print('\nSaved')
print('Program Completed.')
# %%
