# %%
import os
import numpy as np
import pandas as pd
from util import load_pkl
from keras.models import *
from tqdm import tqdm
from collections import defaultdict


cross_num = 10 #int, 用了幾個模型做cross 訓練0~9

# model_name  = 'Annotator_D1-D6_' +str(num_splits)
model_file = './Annotator_Model/'   #改成計算多個模型的平均值並分析標準差
save_folder_path = './result/unlabel_data_predict/'

if not os.path.exists(save_folder_path):
    os.makedirs(save_folder_path)


# %% 对新数据集进行标注
unlabel_path_01 = './data/statistical_results/EMxFC_rk0-20'
# unlabel_path_02 = './data/statistical_results/three_view_pic_rk10to20'

# 筛选出指定文件夹下以 .pkl 结尾的文件並存入列表
file_list_01 = [file_name for file_name in os.listdir(unlabel_path_01) if file_name.endswith('.pkl')]
# file_list_02 = [file_name for file_name in os.listdir(unlabel_path_02) if file_name.endswith('.pkl')]

file_path_01 = [os.path.join(unlabel_path_01, file_name) for file_name in file_list_01]
# file_path_02 = [os.path.join(unlabel_path_02, file_name) for file_name in file_list_02]
file_path = file_path_01 #+ file_path_02


# 计算label

model_lst = []
for i in range(cross_num):
    model_name = 'Annotator_D1-D6_' +str(i)
    model = load_model(model_file + model_name + '.h5')
    model_lst.append(model)


# %%

# 分段完成
sub_length = 2000

if len(file_path) > sub_length:
    
    num = 0
    while num * sub_length < len(file_path):
        start_idx = int(num * sub_length)
        end_idx = int(min((num + 1) * sub_length, len(file_path)))

        file_path_predict = file_path[start_idx:end_idx]
        print('\nProcess on Num.', start_idx, '~', end_idx)


        data_dict = defaultdict((list))  # Initialize dictionaries with default types to store file names and results

        print('Collecting data..')
        # Traverse all entries in the parent folder
        for pkl_file in tqdm(file_path_predict, total=len(file_path_predict)):
            # Load the pkl file
            data_lst = load_pkl(pkl_file)
            for data in data_lst:
                # Record neuron data and stack images
                data_dict['fc_nrn'].append(data[0])
                data_dict['em_nrn'].append(data[1])
                
                # Images generated by Coronation are in the shape of 3,50,50, needed by CNN as 50,50,3
                data_dict['fc_img'].append(np.transpose(data[3], (1, 2, 0)))
                data_dict['em_img'].append(np.transpose(data[4], (1, 2, 0)))
        # print('End collect')

        fc_nrn_lst = data_dict['fc_nrn']
        em_nrn_lst = data_dict['em_nrn']

        # 產生模型輸入numpy array
        fc_img = np.array(data_dict['fc_img'])
        em_img = np.array(data_dict['em_img'])

        print('Model predicting..')
        predict_lst = []
        for model in model_lst:
            predict_result = model.predict({'FC':fc_img, 'EM':em_img}, batch_size=128, verbose=0)
            predict_lst.append(predict_result)
        
        predict_np = np.array(predict_lst)
       
        result_avg = np.mean(predict_np, axis=0)
        result_std = np.std(predict_np, axis=0)
        result_bin = np.where(result_avg > 0.5, 1, 0)

        label_df = pd.DataFrame({'fc_id': fc_nrn_lst, 'em_id': em_nrn_lst, 'model_predict': result_avg.flatten(), 'binary_label': result_bin.flatten(), 'pred_std': result_std.flatten()})

        label_df.to_csv(save_folder_path+'labeled_'+str(num)+'_'+model_name+'.csv', index=False)
        print('\nSave Num:', num)

        num += 1
        # del label_df, data_lst, new_data_lst
    
    print('Program Completed.')

else:
    data_dict = defaultdict((list))  # Initialize dictionaries with default types to store file names and results

    print('Collecting data..')
    # Traverse all entries in the parent folder
    for pkl_file in tqdm(file_path, total=len(file_path)):
        # Load the pkl file
        data_lst = load_pkl(pkl_file)
        for data in data_lst:
            # Record neuron data and stack images
            data_dict['fc_nrn'].append(data[0])
            data_dict['em_nrn'].append(data[1])
            
            # Images generated by Coronation are in the shape of 3,50,50, needed by CNN as 50,50,3
            data_dict['fc_img'].append(np.transpose(data[3], (1, 2, 0)))
            data_dict['em_img'].append(np.transpose(data[4], (1, 2, 0)))
    # print('End collect')

    fc_nrn_lst = data_dict['fc_nrn']
    em_nrn_lst = data_dict['em_nrn']

    # 產生模型輸入numpy array
    fc_img = np.array(data_dict['fc_img'])
    em_img = np.array(data_dict['em_img'])

    print('Model predicting..')
    predict_lst = []
    for model in model_lst:
        predict_result = model.predict({'FC':fc_img, 'EM':em_img}, batch_size=128, verbose=0)
        predict_lst.append(predict_result)
    
    predict_np = np.array(predict_lst)
    
    result_avg = np.mean(predict_np, axis=0)
    result_std = np.std(predict_np, axis=0)
    result_bin = np.where(result_avg > 0.5, 1, 0)

    label_df = pd.DataFrame({'fc_id': fc_nrn_lst, 'em_id': em_nrn_lst, 'model_predict': result_avg.flatten(), 'binary_label': result_bin.flatten(), 'pred_std': result_std.flatten()})

    # 将DataFrame存储为csv文件
    label_df.to_csv(save_folder_path+model_name+'.csv', index=False)
    print('\nSaved')
    print('Program Completed.')
# %%
